# Catppuccino theme scheme for Alacritty

  # base00 = "#1E1D2D",
  # base01 = "#282737",
  # base02 = "#2f2e3e",
  # base03 = "#383747",
  # base04 = "#414050",
  # base05 = "#bfc6d4",
  # base06 = "#ccd3e1",
  # base07 = "#D9E0EE",
  # base08 = "#F38BA8",
  # base09 = "#F8BD96",
  # base0A = "#FAE3B0",
  # base0B = "#ABE9B3",
  # base0C = "#89DCEB",
  # base0D = "#89B4FA",
  # base0E = "#CBA6F7",
  # base0F = "#F38BA8",

[colors.primary]

# background = '#1E1D2D'
# foreground = '#D6D6D6'
# background = '#1E1E2E'

background = '#1E1D2D'
foreground = '#D9E0EE'

[colors.cursor]
text = '#1E1E2E'
cursor = '#D9D9D9'

[colors.normal]
black = '#181A1F'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#ABB2BF'

[colors.bright]
black = '#5C6370'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#F7F7F7'

[colors.dim]
black = '#5C6370'
red = '#74423F'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#6E4962'
cyan = '#5C8482'
white = '#828282'
