[general]
live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "0xff966c"
index = 16

[[colors.indexed_colors]]
color = "0xc53b53"
index = 17

[colors.bright]
black = "0x444a73"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "#C9C8BF"
yellow = "0xffc777"

[colors.cursor]
# cursor = "#4fc2e8"
cursor = "#C9C8BF"
text = "#000000"

[colors.normal]
black = "0x1b1d2b"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "#C9C8BF"
yellow = "0xffc777"

[colors.primary]
foreground = "#C9C8BF"
background = "#031224"

[cursor]
blink_interval = 200
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
blinking = "Never"
shape = "Block"

[debug]
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false

[env]
# TERM = "xterm-256color"
LC_CTYPE = "en_US.UTF-8"

[font]
size = 17.0

[font.normal]
family = "SF Mono"
style = "Regular"


[font.offset]
x = 0
y = 8

[keyboard]
bindings = [
	{ key = "-", mods = "Control", action = "DecreaseFontSize" },
	{ key = "=", mods = "Control", action = "IncreaseFontSize" },
	{ key = "Back", mods = "Alt", chars = "\u0017" },
	{ key = "Back", mods = "Control", chars = "\u0017" },
	{ key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
	{ key = "H", mods = "Control", action = "ReceiveChar" },
	{ key = "H", mods = "Control|Shift", action = "SelectPreviousTab" },
	{ key = "L", mods = "Control|Shift", action = "SelectNextTab" },
	{ key = "Q", mods = "Control", action = "None" },
	{ key = "Space", mods = "Control|Shift", mode = "~Search", action = "ToggleViMode" },
	{ key = "Space", mods = "Control", chars = "\u0000" },
	{ key = "V", mods = "Control|Shift", action = "Paste" },
	{ key = "W", mods = "command|Shift", action = "Quit" },
]

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal]
shell = "wsl.exe ~"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1
blur = true # does not work in windows?
startup_mode = "Maximized"
option_as_alt = "both"

[window.dimensions]
columns = 82
lines = 28

[window.padding]
x = 5
y = 5
