import = [
	"~/.dotfiles/_alacritty-theme/themes/nightfly.toml"
]

live_config_reload = true
working_directory = "None"

[terminal]
# osc52 = "Disabled" | "OnlyCopy" | "OnlyPaste" | "CopyPaste"
osc52 = "CopyPaste"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
blink_interval = 200
unfocused_hollow = true

[colors.cursor]
# cursor = "#db69d7"
# cursor = "#ff52e6"
# cursor = "#ff7fff"
# cursor = "#d586ff" # good color
cursor =  "#5f6060"
text = "#080808"

[colors.primary]
# background = "#181825"
# background = "#23283d" # tokyonight
# foreground = "#c0c9d3"
# background = "#1f2430"
# foreground = "#c2c3c0"

# ayu
# background = "#0a0e13"
# foreground = "#b7b7b7"

# catpuccine
# background = "#21273f"
# foreground = "#b7b7b7"

# nice dark
# background = "#141d26"

# matches kitty
# background = "#162331"

[cursor.style]
blinking = "Never"
shape = "Block"

[debug]
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 22.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MonolisaLiga Nerd Font"
style = "Medium Regular"

# [font.italic]
# family = "MonolisaLiga Nerd Font"
# style = "Italic"
#
[font.bold]
family = "MonolisaLiga Nerd Font"

[font.offset]
x = 0
y = 10

# https://www.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "CreateNewTab"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SelectPreviousTab"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SelectNextTab"
key = "L"
mods = "Control|Shift"

# toggle simple full screen
[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control|Shift"

# hide all other apps except alacritty
# [[keyboard.bindings]]
# action = "HideOtherApplications"
# key = "H"
# mods = "Command|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Alt"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true
# semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
# decorations = "buttonless"
decorations = "Full"
dynamic_padding = true
dynamic_title = true
opacity = 0.70
blur = true

startup_mode = "Windowed"
option_as_alt = "both"

[window.dimensions]
columns = 82
lines = 28

[window.padding]
x = 5
y = 5
