live_config_reload = true
working_directory = "None"

[terminal]
# osc52 = "Disabled" | "OnlyCopy" | "OnlyPaste" | "CopyPaste"
osc52 = "CopyPaste"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[colors.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[colors.primary]
background = "#011627"
foreground = "#bdc1c6"

# background  = "#19202f"
# foreground  = "#afb2c6"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[cursor]
blink_interval = 200
unfocused_hollow = true

[colors.cursor]
cursor =  "#5f6060"
text = "#080808"

[cursor.style]
blinking = "Never"
shape = "Block"

[debug]
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false

# transparency may not work with this enabled in linux
prefer_egl = true

[env]
TERM = "xterm-256color"

[font]
size = 22.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MonolisaNoLiga Nerd Font"
style = "Medium Regular"

[font.offset]
x = 0
y = 10

# https://www.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/

[keyboard]
bindings = [
  {  key  =  "V",     mods  =  "Command|Shift",  action  =  "Paste"              },
  {  key  =  "T",     mods  =  "Command|Shift",  action  =  "CreateNewTab"       },
  {  key  =  "H",     mods  =  "Command|Shift",  action  =  "SelectPreviousTab"  },
  {  key  =  "L",     mods  =  "Command|Shift",  action  =  "SelectNextTab"      },
  {  key  =  "F",     mods  =  "Command|Shift",  action  =  "ToggleFullscreen"   },
  {  key  =  "Back",  mods  =  "Alt",            chars   =  "\u0017"             },
  {  key  =  "Back",  mods  =  "Command",        chars   =  "\u0017"             },
  {  key  =  "=",     mods  =  "Command",        action  =  "IncreaseFontSize"   },
  {  key  =  "-",     mods  =  "Command",        action  =  "DecreaseFontSize"   },
  {  key  =  "K",     mods  =  "Command|Shift",  chars   =  "\u000c"             },
    { key = "C", mods = "Command", chars = "\u0003" },
   { key = "V", mods = "Command", chars = "\u0016" },
   { key = "Slash", mods = "Command", chars = "\u001f" },
   { key = "N", mods = "Command", chars = "\u000e" },
   { key = "P", mods = "Command", chars = "\u0010" },
   { key = "J", mods = "Command", chars = "\u000a" },
   { key = "K", mods = "Command", chars = "\u000b" },
   { key = "L", mods = "Command", chars = "\u000c" },
   { key = "H", mods = "Command", chars = "\u0008" },
   { key = "A", mods = "Command", chars = "\u0001" },
   { key = "X", mods = "Command", chars = "\u0018" },
   { key = "D", mods = "Command", chars = "\u0004" },
   { key = "F", mods = "Command", chars = "\u0006" },
   { key = "S", mods = "Command", chars = "\u0013" },
   { key = "E", mods = "Command", chars = "\u0005" },
   { key = "Space", mods = "Command", chars = "\u0000" },
    { key = "R", mods = "Command", chars = "\u0012" },
    { key = "I", mods = "Command", chars = "\u0009" },
]

[mouse]
hide_when_typing = true
bindings = [
  {  action  =  "PasteSelection",  mouse  =  "Middle"  }
]

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
# decorations = "buttonless"
decorations = "Full"
dynamic_padding = true
dynamic_title = true
opacity = 0.90
blur = true

startup_mode = "Windowed"
option_as_alt = "both"

[window.dimensions]
columns = 82
lines = 28

[window.padding]
x = 5
y = 5


