#!/bin/sh

# Get the first 4 modified files
files=$(git diff --cached --name-only | head -n 4)

# Construct the commit message
if [ -n "$files" ]; then
  echo "Update $(echo "$files" | sed 's/\n/, /g')" > "$1"
fi
