# SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
# filename = "{{slug title}}-{{id}}"
filename = "{{slug title}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 5

# Letter case for the random IDs.
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "Jose Lima"


# GROUP OVERRIDES
[group.standup]
paths = ["notes/standup"]

[group.standup.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "standup.md"

[group.daily]
paths = ["journal"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]

# Edit the last modified note.
l = "zk edit --limit 1 --sort modified- $@"
last = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# list notes for editing
ls = "zk edit --interactive"
g = "zk edit --interactive $HOME/games"

# list = "zk edit --interactive"

# sear notes by tags
t = 'zk list --interactive -t "$*"'

config = 'nvim "$HOME/.dotfiles/zk/config.toml"'

# new journal entry
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'

# new note
ne = 'zk new --no-input "$ZK_NOTEBOOK_DIR/ideas" --title "$*"'

n = 'zk new --no-input --title "$*"'

# new standup entry
standup = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Standup"'

# list standup
ls-standup = 'zk edit "$ZK_NOTEBOOK_DIR/standup" --sort created- --interactive'

journal = "zk edit --sort created- $ZK_NOTEBOOK_DIR/journal --interactive"

ideas = "zk edit --sort created- $ZK_NOTEBOOK_DIR/ideas --interactive"

# update zk notes
update = "cd $ZK_NOTEBOOK_DIR; git pull; git add -A; git commit -am 'updating'; git push; cd -"
up = "cd $ZK_NOTEBOOK_DIR; git pull; git add -A; git commit -am 'updating'; git push; cd -"
u = "if [ -d .zk ]; then git pull; git add -A; git commit -am 'updating'; git push; cd -; fi"

pull = "cd $ZK_NOTEBOOK_DIR; git pull; cd -"

# remove a files
rm = "zk list --interactive --quiet --format path --delimiter0 $@ | xargs -0 rm -vf --"

# open last zk in slides
slides = "zk list --interactive --quiet --format path --delimiter0 $@ | xargs -0 slides"

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
