vim.filetype.add({
  filename = {
    ["Jenkinsfile"] = "groovy",
    ["Jenkinsfile-1"] = "groovy",
    ["Jenkinsfile-2"] = "groovy",
    ["Jenkinsfile-3"] = "groovy",
    ["Jenkinsfile-4"] = "groovy",
    [".env"] = "dotenv",
    ["env"] = "dotenv",
  },
  pattern = {
    ["[jt]sconfig.*.json"] = "jsonc",
    ["%.env%.[%w_.-]+"] = "dotenv",
  },
  extension = {
    env = "dotenv",
    csv = "csv",
    cl = "opencl",
    gohtml = "html",
    j2 = "jinja",
    conf = "config",
    yml = "yaml.ansible",
    yaml = "yaml.ansible",
    md = "markdown",
    ts = "typescript",
    tf = "terraform",
    tfvars = "terraform",
    tfstate = "json",
    hcl = "terraform",
    asm = "nasm",
  },
})
