vim.filetype.add({
  filename = {
    ["Jenkinsfile"] = "groovy",
    ["Jenkinsfile-1"] = "groovy",
    ["Jenkinsfile-2"] = "groovy",
    ["Jenkinsfile-3"] = "groovy",
    ["Jenkinsfile-4"] = "groovy",
    [".env"] = "dotenv",
    ["env"] = "dotenv",
    [".eslintrc"] = "json",
    [".prettierrc"] = "json",
    [".babelrc"] = "json",
    [".stylelintrc"] = "json",
  },
  pattern = {
    ["[jt]sconfig.*.json"] = "jsonc",
    [".*%.cfg"] = "ini",
    ["%.env%.[%w_.-]+"] = "dotenv",
    [".*config/git/config"] = "gitconfig",
    [".env.*"] = "sh",
  },
  extension = {
    env = "dotenv",
    csv = "csv",
    cl = "opencl",
    gohtml = "html",
    j2 = "jinja",
    conf = "config",
    yml = "yaml",
    -- yaml = "yaml.ansible",
    md = "markdown",
    ts = "typescript",
    tf = "terraform",
    tfvars = "terraform",
    tfstate = "json",
    hcl = "terraform",
    asm = "nasm",
    es6 = "javascript",
    mts = "typescript",
    cts = "typescript",
  },
})
