---
# /root/docker-compose-wireguard.yml
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Madrid
      - SERVERURL=<chageme.to.something.com>
      - SERVERPORT=51820
      - PEERS=8
      - PEERDNS=192.168.212.171
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /root/wireguard_config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
# this is the systemd service file needed
# /etc/systemd/system/wireguard.service
# [Unit]
# Description=Wireguard service
# After=docker.service
# Requires=docker.service
#
# [Service]
# Type=oneshot
# RemainAfterExit=yes
# ExecStart=/bin/bash -c "docker compose -f /root/docker-compose-wireguard.yml up --detach"
# ExecStop=/bin/bash -c "docker compose -f /root/docker-compose-wireguard.yml stop"
#
# [Install]
# WantedBy=multi-user.target
