---
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Madrid
      # change me
      - SERVERURL=server.com
      - SERVERPORT=51820
      - PEERS=8
      - PEERDNS=192.168.212.171
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /root/wireguard_config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
