---
extends: default

ignore:
  - /this/specific/file.yaml
  - all/this/directory/
  - '*.template.yaml'
  - venv/

rules:
  line-length:
    max: 120
    level: warning
  empty-lines:
    max: 1
    level: warning
