aliases: {}
substitute-path: []
max-string-len: 200
max-array-values: 100
show-location-expr: false
source-list-line-color: null
source-list-arrow-color: "\e[93m"
source-list-keyword-color: "\e[0m"
source-list-string-color: "\e[92m"
source-list-number-color: "\e[0m"
source-list-comment-color: "\e[95m"
prompt-color: ""
source-list-tab-color: "\e[90m"
stacktrace-function-color: ""
stacktrace-basename-color: ""
position: ""
tab: ""
trace-show-timestamp: false
